[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.18'

[rpc_endpoints]
moonbase = "https://rpc.api.moonbase.moonbeam.network"
moonbeam = "https://rpc.api.moonbeam.network"

[etherscan]
moonbase = { key = "TWSXD5HVFDPRIKMW9T9E6VG3TSBWAS7XAM" }
moonbeam = { key = "TWSXD5HVFDPRIKMW9T9E6VG3TSBWAS7XAM" }
